"""The ``MEMORY.md`` store — the agent's own long-term memory (GOAL's contract).

Owns the live memory file (``workspace/memory/MEMORY.md`` in the standard layout; the
composition root's ``build_memory`` resolves the path and seeds it from the committed
``MEMORY.seed.md`` on first run): loaded on start (created from a four-section template if
missing), appended to during research, and reorganized at close. Reorganization refreshes the
Champions section from the registry, dedups learnings, prunes to a size budget, and keeps a
dated changelog — all rule-based, no network. LLM memory upkeep is stage-2 distillation
(:mod:`noctis.research.distill`), which runs behind the provider-neutral client seam and
writes back through :meth:`MemoryStore.set_distilled`.
"""

from __future__ import annotations

import json
import re
from datetime import UTC, datetime
from pathlib import Path

SECTION_ORDER = ["Champions", "Learnings", "Rejected ideas", "Index / changelog"]

# The machine-owned section stage-2 distillation regenerates wholesale (context plan P3).
# Deliberately NOT in SECTION_ORDER: it exists only once a distillation has run, so files
# that never distill are never rewritten with an empty extra section.
DISTILLED_SECTION = "Distilled lessons"
_DISTILLED_MARKER = (
    "_(machine-owned: regenerated by memory distillation — edits here are overwritten)_"
)

_TEMPLATE = """# MEMORY

> Noctis's own long-term memory. Loaded at start of every run, appended during
> research, reorganized and compacted at each market close. Kept small and useful.

## Champions

_(none yet.)_

## Learnings

_(none yet.)_

## Rejected ideas

_(none yet.)_

## Index / changelog

- {date} — Memory initialized.
"""

_PLACEHOLDER = re.compile(r"^_.*_$")
_REJECTED_RE = re.compile(r"`([^`]+)`\s*(\{.*\})")


def _today() -> str:
    return datetime.now(UTC).date().isoformat()


class MemoryStore:
    """File-backed implementation of the :class:`~noctis.memory.base.Memory` protocol."""

    def __init__(
        self,
        path: str | Path,
        max_lines: int = 200,
    ):
        self.path = Path(path)
        self.max_lines = max_lines
        self.preamble: str = ""
        self.sections: dict[str, list[str]] = {name: [] for name in SECTION_ORDER}
        self.load()

    # --- load / parse / write ---
    def load(self) -> None:
        if not self.path.is_file():
            self.path.parent.mkdir(parents=True, exist_ok=True)
            self.path.write_text(_TEMPLATE.format(date=_today()), encoding="utf-8")
        self._parse(self.path.read_text(encoding="utf-8"))

    def _parse(self, text: str) -> None:
        self.sections = {name: [] for name in SECTION_ORDER}
        preamble_lines: list[str] = []
        current: str | None = None
        for line in text.splitlines():
            if line.startswith("## "):
                current = line[3:].strip()
                if current not in self.sections:
                    self.sections[current] = []
                continue
            if current is None:
                preamble_lines.append(line)
            else:
                if line.strip():  # keep non-empty content lines only
                    self.sections[current].append(line)
        self.preamble = "\n".join(preamble_lines).strip()

    def _render(self) -> str:
        parts = [self.preamble, ""]
        names = SECTION_ORDER + [n for n in self.sections if n not in SECTION_ORDER]
        for name in names:
            parts.append(f"## {name}")
            parts.append("")
            body = self.sections.get(name, [])
            parts.extend(body if body else ["_(none yet.)_"])
            parts.append("")
        return "\n".join(parts).rstrip() + "\n"

    def _write(self) -> None:
        tmp = self.path.with_suffix(".md.tmp")
        tmp.write_text(self._render(), encoding="utf-8")
        tmp.replace(self.path)

    @staticmethod
    def _clean(lines: list[str]) -> list[str]:
        """Drop italic placeholder lines like ``_(none yet.)_``."""
        return [ln for ln in lines if not _PLACEHOLDER.match(ln.strip())]

    # --- Memory protocol ---
    def append_finding(self, note: str) -> None:
        section = self._clean(self.sections["Index / changelog"])
        section.append(f"- {_today()} — {note}")
        self.sections["Index / changelog"] = section
        self._write()

    def record_rejected(self, family: str, params: dict, reason: str = "") -> None:
        section = self._clean(self.sections["Rejected ideas"])
        encoded = json.dumps(params, sort_keys=True)
        suffix = f" — {reason}" if reason else ""
        section.append(f"- `{family}` {encoded}{suffix}")
        self.sections["Rejected ideas"] = section
        self._write()

    def rejected_ideas(self) -> list[dict]:
        out: list[dict] = []
        for line in self.sections.get("Rejected ideas", []):
            m = _REJECTED_RE.search(line)
            if m:
                try:
                    out.append({"family": m.group(1), "params": json.loads(m.group(2))})
                except json.JSONDecodeError:
                    continue
        return out

    def findings(self) -> list[str]:
        """The changelog notes ``append_finding`` records (promotions, dead ends, minted
        spec-families) — surfaced in the close-of-day report."""
        return list(self._clean(self.sections.get("Index / changelog", [])))

    def add_learning(self, note: str) -> None:
        section = self._clean(self.sections["Learnings"])
        section.append(f"- {note}")
        self.sections["Learnings"] = section
        self._write()

    # --- distilled lessons (stage-2 memory distillation, context plan P3) ---
    def set_distilled(self, lines: list[str]) -> None:
        """Replace the machine-owned distilled block in place. The section IS the fence:
        regeneration swaps its whole body and ``_write`` re-renders every other section
        byte-identically, so nothing outside it is ever touched."""
        bullets = [ln if ln.lstrip().startswith("- ") else f"- {ln}" for ln in lines if ln.strip()]
        self.sections[DISTILLED_SECTION] = [_DISTILLED_MARKER, *bullets]
        self._write()

    def distilled(self) -> list[str]:
        """The distilled-lessons bullets (without the ownership marker); [] if never distilled."""
        lines = self.sections.get(DISTILLED_SECTION, [])
        return [ln for ln in lines if ln.lstrip().startswith("- ")]

    # --- reorganization ---
    def reorganize(self, registry=None) -> None:
        """Refresh champions, dedup, and enforce the size budget."""
        if registry is not None:
            self.sections["Champions"] = self._champion_lines(registry)

        self.sections["Learnings"] = self._dedup(self._clean(self.sections["Learnings"]))
        self.sections["Rejected ideas"] = self._dedup(self._clean(self.sections["Rejected ideas"]))

        self._enforce_budget()
        self._write()

    @staticmethod
    def _champion_lines(registry) -> list[str]:
        lines = []
        for entry in registry.list():
            lines.append(
                f"- `{entry.family}` {json.dumps(entry.params, sort_keys=True)} — "
                f"test={entry.test_metric:.4f} gap={entry.gap:.4f} "
                f"(crowned {entry.crowned_at[:10]}): {entry.rationale}"
            )
        return lines

    @staticmethod
    def _dedup(lines: list[str]) -> list[str]:
        seen: set[str] = set()
        out: list[str] = []
        for ln in lines:
            key = ln.strip()
            if key not in seen:
                seen.add(key)
                out.append(ln)
        return out

    _MARKER = "- (older changelog entries pruned:"

    def _enforce_budget(self) -> None:
        """Drop oldest entries until budget: changelog first, then rejected ideas, learnings.

        Champions are never pruned — the registry is authoritative and the section is
        already capped by ``champion_count``.
        """
        changelog = self._clean(self.sections["Index / changelog"])
        pruned = 0
        body: list[str] = []
        for ln in changelog:
            if ln.startswith(self._MARKER):
                m = re.search(r"pruned: (\d+)", ln)
                pruned += int(m.group(1)) if m else 0
            else:
                body.append(ln)

        def commit() -> None:
            marker = [f"{self._MARKER} {pruned})"] if pruned else []
            self.sections["Index / changelog"] = marker + body

        commit()
        # Remove the oldest real entry each pass; the marker stays a single line, so the
        # section shrinks by one line per pass and the loop always terminates.
        while self._total_lines() > self.max_lines and body:
            body.pop(0)
            pruned += 1
            commit()

        # Changelog exhausted but still over budget → drop the oldest rejected ideas,
        # then the oldest learnings, so the file converges under max_lines.
        for name in ("Rejected ideas", "Learnings"):
            section = self._clean(self.sections[name])
            self.sections[name] = section
            while self._total_lines() > self.max_lines and section:
                section.pop(0)

    def _total_lines(self) -> int:
        return len(self._render().splitlines())

    def read(self) -> str:
        return self.path.read_text(encoding="utf-8")
